version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: urlshortener_db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: ./src/web/Dockerfile
    container_name: urlshortener_app
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__UrlShortenerDb: "Server=urlshortener_db;Database=URLShortenerDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
